name: Add Platform Label
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Platform: Xamarin"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
